- name: Download Docker dependencies
  get_url:
    url: "{{ item }}"
    dest: /tmp/
  with_items:
    - https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/containerd.io_1.2.6-3_amd64.deb
    - https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce-cli_19.03.5~3-0~ubuntu_amd64.deb
    - https://download.docker.com/linux/ubuntu/dists/bionic/pool/stable/amd64/docker-ce_19.03.5~3-0~ubuntu_amd64.deb

- name: Copy Docker dependencies to remote server
  synchronize:
    src: /tmp/{{ item }}
    dest: /tmp/
  with_items:
    - containerd.io_1.2.6-3_amd64.deb
    - docker-ce-cli_19.03.5~3-0~ubuntu_amd64.deb
    - docker-ce_19.03.5~3-0~ubuntu_amd64.deb
  delegate_to: remote_server

- hosts: remote_server
  tasks:
    - name: Install Docker dependencies
      apt:
        deb: /tmp/{{ item }}
      with_items:
        - containerd.io_1.2.6-3_amd64.deb
        - docker-ce-cli_19.03.5~3-0~ubuntu_amd64.deb
        - docker-ce_19.03.5~3-0~ubuntu_amd64.deb

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

